#!/bin/bash
SCHEMA=$1
TABLE=$2
FILEPARAMETERS=$3

export $(xargs <$FILEPARAMETERS.sh)

QUERY="UNLOAD ('SELECT * FROM ${SCHEMA}.${TABLE}')
  TO '${S3_BUCKET_BASE}/${DB}/'
  CREDENTIALS 'aws_iam_role=${IAM_ROLE}'
  CLEANPATH
  DELIMITER '|'
  GZIP;"

export PGPASSWORD="$REDSHIFT_PASSWORD"
/usr/bin/psql -h "$REDSHIFT_IP" -p "$REDSHIFT_PORT" -U "$REDSHIFT_USER" -d "$DB" -c "$QUERY"