steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/teamcore-multi/tc-infra/db-backup:0.52', '.' ]
images:
  - 'us-central1-docker.pkg.dev/teamcore-multi/tc-infra/db-backup:0.52'