variable "project" {}
variable "region" {}
variable "zone" {}
variable "network" {}
variable "cluster_name" {}
variable "env_name" {}
variable "origen_project" {}
variable "origen_region" {}
variable "origen_instance" {}
variable "origen_db" {}
variable "origen_password" {}
variable "destinity_super_password" {}
variable "destinity_user" {}
variable "destinity_password" {}
variable "destinity_pg_version" {}
variable "pub_key" {}
variable "account_id" {}
variable "pg_bouncer_pass" {}