name: Generate CHANGELOG

on:
  push:
    tags:
      - 'v*'  # Activa el workflow cuando se crea un tag que comienza con 'v'
  release:
    types: [published] 

jobs:
  generate_changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Necesario para obtener el historial completo de Git

      - name: Generar Changelog
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Obtiene la última etiqueta (o usa un punto de referencia)
          last_tag=$(git describe --tags --abbrev=0)

          # Obtiene los commits desde la última etiqueta hasta HEAD
          commits=$(git log --pretty=format:"%h - %s" ${last_tag}..HEAD)

          # Genera el changelog
          echo "# Changelog" > CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "## Cambios desde la versión ${last_tag}" >> CHANGELOG.md
          echo "" >> CHANGELOG.md

          if [[ -z "$commits" ]]; then
            echo "No hay cambios desde la última versión." >> CHANGELOG.md
          else
            echo "$commits" >> CHANGELOG.md
          fi

      - name: Commit y Push del Changelog
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "ci.cd@teamcore.net"
          git add CHANGELOG.md
          git commit -m "Actualiza CHANGELOG.md con los cambios del lanzamiento"
          git push origin HEAD:${GITHUB_REF##*/}